name: Build Nova AI APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git unzip wget
        sudo apt-get install -y default-jdk default-jre
        sudo apt-get install -y libssl-dev libffi-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        pip install kivy kivymd

    - name: Set up Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477380_latest.zip
        unzip -q commandlinetools-linux-9477380_latest.zip
        sudo mv cmdline-tools /usr/local/android-sdk/
        echo "y" | /usr/local/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/android-sdk "platforms;android-31" "build-tools;31.0.0"
        echo "y" | /usr/local/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/android-sdk "ndk;25.1.8937393"

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK_ROOT=/usr/local/android-sdk/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/platform-tools" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: nova-ai-apk
        path: bin/*.apk
        retention-days: 30

    - name: Get APK info
      run: |
        ls -la bin/
        file bin/*.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        draft: false
        prerelease: false
